### PR TITLE
table word wrap fix

### PR DESCRIPTION
**Pull request by TiagoF99**
addressed issue outlined here: https://github.com/OpenLiberty/guide-microprofile-jwt/issues/70

### CODE REVIEW

**Comment by AustinSeto** [comment]
Verified appearance of table, is half screen width as expected

LGTM

**Comment by TiagoF99** [comment]
@gkwan-ibm I noticied that when i made the width smaller for the first column, that it was very hard to read when the screen was resized. Do you have suggested ratio for the column widths? (like right now it is 50/50, do you suggest 40/60 or 30/70)

**Comment by gkwan-ibm** [comment]
@TiagoF99 using ratio or whatever way is fine. What's the ratio? Would you find it out with best look?

**Comment by TiagoF99** [comment]
I will investigate

**Comment by TiagoF99** [comment]
Screen Shot 2020-07-13 at 3 15 02 PM
- it now looks like this. This also keeps it readable when sizing the screen

**Comment by DannyS03** [comment]
tested/verified on **qa**.

**Pull request merged**
